"""Model eğitim ekranı için Nasdaq-100 şirket kataloğu."""

# Nasdaq-100 büyük şirket evreninin uygulama içi 2026-07 görünümü.
NASDAQ_100 = [
    ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corporation"),
    ("NVDA", "NVIDIA Corporation"), ("AMZN", "Amazon.com, Inc."),
    ("GOOGL", "Alphabet Inc. Class A"), ("GOOG", "Alphabet Inc. Class C"),
    ("META", "Meta Platforms, Inc."), ("AVGO", "Broadcom Inc."),
    ("TSLA", "Tesla, Inc."), ("COST", "Costco Wholesale Corporation"),
    ("NFLX", "Netflix, Inc."), ("ASML", "ASML Holding N.V."),
    ("PLTR", "Palantir Technologies Inc."), ("AMD", "Advanced Micro Devices, Inc."),
    ("CSCO", "Cisco Systems, Inc."), ("TMUS", "T-Mobile US, Inc."),
    ("AZN", "AstraZeneca PLC"), ("LIN", "Linde plc"),
    ("PEP", "PepsiCo, Inc."), ("INTU", "Intuit Inc."),
    ("ISRG", "Intuitive Surgical, Inc."), ("BKNG", "Booking Holdings Inc."),
    ("AMGN", "Amgen Inc."), ("QCOM", "QUALCOMM Incorporated"),
    ("TXN", "Texas Instruments Incorporated"), ("AMAT", "Applied Materials, Inc."),
    ("HON", "Honeywell International Inc."), ("SHOP", "Shopify Inc."),
    ("ARM", "Arm Holdings plc"), ("APP", "AppLovin Corporation"),
    ("MU", "Micron Technology, Inc."), ("PANW", "Palo Alto Networks, Inc."),
    ("ADP", "Automatic Data Processing, Inc."), ("GILD", "Gilead Sciences, Inc."),
    ("MELI", "MercadoLibre, Inc."), ("KLAC", "KLA Corporation"),
    ("LRCX", "Lam Research Corporation"), ("SBUX", "Starbucks Corporation"),
    ("CRWD", "CrowdStrike Holdings, Inc."), ("MSTR", "Strategy Inc."),
    ("ADI", "Analog Devices, Inc."), ("CEG", "Constellation Energy Corporation"),
    ("DASH", "DoorDash, Inc."), ("MAR", "Marriott International, Inc."),
    ("MDLZ", "Mondelez International, Inc."), ("SNPS", "Synopsys, Inc."),
    ("CDNS", "Cadence Design Systems, Inc."), ("CTAS", "Cintas Corporation"),
    ("REGN", "Regeneron Pharmaceuticals, Inc."), ("ABNB", "Airbnb, Inc."),
    ("ORLY", "O'Reilly Automotive, Inc."), ("MRVL", "Marvell Technology, Inc."),
    ("FTNT", "Fortinet, Inc."), ("CPRT", "Copart, Inc."),
    ("PCAR", "PACCAR Inc"), ("ROP", "Roper Technologies, Inc."),
    ("ADSK", "Autodesk, Inc."), ("NXPI", "NXP Semiconductors N.V."),
    ("MNST", "Monster Beverage Corporation"), ("AEP", "American Electric Power Company, Inc."),
    ("PAYX", "Paychex, Inc."), ("FAST", "Fastenal Company"),
    ("IDXX", "IDEXX Laboratories, Inc."), ("KDP", "Keurig Dr Pepper Inc."),
    ("TEAM", "Atlassian Corporation"), ("CHTR", "Charter Communications, Inc."),
    ("MCHP", "Microchip Technology Incorporated"), ("VRSK", "Verisk Analytics, Inc."),
    ("EXC", "Exelon Corporation"), ("EA", "Electronic Arts Inc."),
    ("CSX", "CSX Corporation"), ("BKR", "Baker Hughes Company"),
    ("XEL", "Xcel Energy Inc."), ("GEHC", "GE HealthCare Technologies Inc."),
    ("KHC", "The Kraft Heinz Company"), ("FANG", "Diamondback Energy, Inc."),
    ("CCEP", "Coca-Cola Europacific Partners PLC"), ("TTWO", "Take-Two Interactive Software, Inc."),
    ("WBD", "Warner Bros. Discovery, Inc."), ("DXCM", "DexCom, Inc."),
    ("ODFL", "Old Dominion Freight Line, Inc."), ("ZS", "Zscaler, Inc."),
    ("DDOG", "Datadog, Inc."), ("ALNY", "Alnylam Pharmaceuticals, Inc."),
    ("FER", "Ferrovial SE"), ("INSM", "Insmed Incorporated"),
    ("MPWR", "Monolithic Power Systems, Inc."), ("STX", "Seagate Technology Holdings plc"),
    ("WDC", "Western Digital Corporation"), ("SNDK", "Sandisk Corporation"),
    ("LITE", "Lumentum Holdings Inc."), ("VRTX", "Vertex Pharmaceuticals Incorporated"),
    ("PDD", "PDD Holdings Inc."), ("ROST", "Ross Stores, Inc."),
    ("CSGP", "CoStar Group, Inc."), ("ON", "ON Semiconductor Corporation"),
    ("GFS", "GlobalFoundries Inc."), ("TTD", "The Trade Desk, Inc."),
    ("BIIB", "Biogen Inc."), ("LULU", "lululemon athletica inc."),
]

assert len(NASDAQ_100) == 100
assert len({ticker for ticker, _ in NASDAQ_100}) == 100
